向量,矩阵,数组,dataframe,list

In [3]:
x <- 1:10;
print(x) 

 [1]  1  2  3  4  5  6  7  8  9 10


In [4]:
x <- c(1,2,3,4,5);
print(x) 

[1] 1 2 3 4 5


In [5]:
x <- seq(from=1,to=10);
print(x) 

 [1]  1  2  3  4  5  6  7  8  9 10


In [6]:
x <- seq(from=1,to=10,by=2);
print(x) 

[1] 1 3 5 7 9


In [8]:
x <- seq(from=1,to=10,length.out=20);
print(x) 

 [1]  1.000000  1.473684  1.947368  2.421053  2.894737  3.368421  3.842105
 [8]  4.315789  4.789474  5.263158  5.736842  6.210526  6.684211  7.157895
[15]  7.631579  8.105263  8.578947  9.052632  9.526316 10.000000


In [11]:
# 生成日期变量并用生成的日期变量生成一组日期序列数据： 
s <- as.Date('2014-1-1') 
e <- as.Date('2014-2-1') 
dtVec <- seq(from=s,to=e,by=1) 
print(dtVec) 
print(class(dtVec)) 

 [1] "2014-01-01" "2014-01-02" "2014-01-03" "2014-01-04" "2014-01-05"
 [6] "2014-01-06" "2014-01-07" "2014-01-08" "2014-01-09" "2014-01-10"
[11] "2014-01-11" "2014-01-12" "2014-01-13" "2014-01-14" "2014-01-15"
[16] "2014-01-16" "2014-01-17" "2014-01-18" "2014-01-19" "2014-01-20"
[21] "2014-01-21" "2014-01-22" "2014-01-23" "2014-01-24" "2014-01-25"
[26] "2014-01-26" "2014-01-27" "2014-01-28" "2014-01-29" "2014-01-30"
[31] "2014-01-31" "2014-02-01"
[1] "Date"


In [4]:
x = gl(2,5) #gl是一个函数
x

[1] 1 1 1 1 1 2 2 2 2 2
Levels: 1 2

In [5]:
class(x)

[1] "factor"

In [6]:
mode(x)

[1] "numeric"

In [7]:
typeof(x)

[1] "integer"

In [1]:
x <- 1:10;
print(x) 

 [1]  1  2  3  4  5  6  7  8  9 10


In [2]:
# R语言中的索引从1开始
print(x[5]) 
print(x[-5]) 

[1] 5
[1]  1  2  3  4  6  7  8  9 10


In [3]:
print(x[c(1,5,8)]) 
print(x[1:5]) 

[1] 1 5 8
[1] 1 2 3 4 5


In [4]:
print(x[1:5*2]) # 冒号优先级更高，首先得到1-5这5个数据再乘以2 

[1]  2  4  6  8 10


In [5]:
print(x[ x > 5 ]) # 逻辑表达式用x中每一个元素计算逻辑表达式的值做索引，得到的是原数组中x大于5的元素 

[1]  6  7  8  9 10


In [6]:
print(mean(x)) 
print(x[ x > mean(x) ] ) # 逻辑表达中可以使用函数 

[1] 5.5
[1]  6  7  8  9 10


In [7]:
names(x) <- LETTERS[1:10];
print(x) # 使用字符常数数组给向量命名，再通过变量名访问向量中的元素 

 A  B  C  D  E  F  G  H  I  J 
 1  2  3  4  5  6  7  8  9 10 


In [10]:
print(x['A']) 

A 
1 


In [11]:
View(x) # x有点类似字典

ERROR: Error in View(x): 'View()' not yet supported in the Jupyter R kernel


In [12]:
print(length(x))

[1] 10


In [13]:
x <- 1:10;
print(x) 
x[5] <- 100;
print(x)

 [1]  1  2  3  4  5  6  7  8  9 10
 [1]   1   2   3   4 100   6   7   8   9  10


In [14]:
x <- 1:10;
print(x) 
x <- c(x,11,12,13);
print(x)

 [1]  1  2  3  4  5  6  7  8  9 10
 [1]  1  2  3  4  5  6  7  8  9 10 11 12 13


In [15]:
x <- 1:10;
print(x) 
x[length(x)+1] <- 11;
print(x)

 [1]  1  2  3  4  5  6  7  8  9 10
 [1]  1  2  3  4  5  6  7  8  9 10 11


并不是在原来的向量中插入数据而是返回一个新的向量  
after参数表示在原向量中的那个向量后面插入数据 

In [16]:
x <- 1:10;
print(x) 
y <- append(x,11:13,after=0);
print(x);
print(y) 
y <- append(x,11:13,after=5);
print(x);
print(y)

 [1]  1  2  3  4  5  6  7  8  9 10
 [1]  1  2  3  4  5  6  7  8  9 10
 [1] 11 12 13  1  2  3  4  5  6  7  8  9 10
 [1]  1  2  3  4  5  6  7  8  9 10
 [1]  1  2  3  4  5 11 12 13  6  7  8  9 10


In [14]:
# 数组 
# 生成向量然后通过设置行列数据转换成二维数组 
x <- 1:20 
dim(x) <- c(5,4) 
print(x) 

     [,1] [,2] [,3] [,4]
[1,]    1    6   11   16
[2,]    2    7   12   17
[3,]    3    8   13   18
[4,]    4    9   14   19
[5,]    5   10   15   20


In [15]:
x <- array(3.14,dim=c(5,4)) 
print(x) 

     [,1] [,2] [,3] [,4]
[1,] 3.14 3.14 3.14 3.14
[2,] 3.14 3.14 3.14 3.14
[3,] 3.14 3.14 3.14 3.14
[4,] 3.14 3.14 3.14 3.14
[5,] 3.14 3.14 3.14 3.14


In [16]:
# 可以生成三维数组 
# 使用正态分布随机数初始化整个数组 
#  rnorm(n=40,mean=10,sd=5)
x <- array(rnorm(40,10,5),dim=c(5,4,2)) 
print(x) 
print(length(x)) 
# 对于矩阵length()函数得到的是所有元素的总数量

, , 1

          [,1]      [,2]      [,3]      [,4]
[1,] 11.739859 14.671944 16.043055  4.474288
[2,]  8.392017 13.108677  6.285443  8.783863
[3,] 12.678970 10.834419 14.227438 16.491985
[4,] 18.182335 12.881927 22.191449  5.994543
[5,]  8.866629  5.770009 16.437035 17.510703

, , 2

          [,1]      [,2]      [,3]      [,4]
[1,] 0.3057222  6.711887  7.229127  9.155751
[2,] 8.9476973 16.028550 18.465106 12.385906
[3,] 4.1443411 13.125212 18.698592 11.844463
[4,] 7.6627066 11.949013  8.229086 11.646247
[5,] 1.1682728  4.520407  9.066174  3.367711

[1] 40


In [1]:
# 矩阵访问
data(EuStockMarkets) # EuStockMarkets 是本地R里面自带的
print(head(EuStockMarkets)) 
print(class(EuStockMarkets)) 

         DAX    SMI    CAC   FTSE
[1,] 1628.75 1678.1 1772.8 2443.6
[2,] 1613.63 1688.5 1750.5 2460.2
[3,] 1606.51 1678.6 1718.0 2448.2
[4,] 1621.04 1684.1 1708.1 2470.4
[5,] 1618.16 1686.6 1723.1 2484.7
[6,] 1610.61 1671.6 1714.3 2466.8
[1] "mts"    "ts"     "matrix"


In [2]:
print(summary(EuStockMarkets)) # 自动计算统计参数

      DAX            SMI            CAC            FTSE     
 Min.   :1402   Min.   :1587   Min.   :1611   Min.   :2281  
 1st Qu.:1744   1st Qu.:2166   1st Qu.:1875   1st Qu.:2843  
 Median :2141   Median :2796   Median :1992   Median :3247  
 Mean   :2531   Mean   :3376   Mean   :2228   Mean   :3566  
 3rd Qu.:2722   3rd Qu.:3812   3rd Qu.:2274   3rd Qu.:3994  
 Max.   :6186   Max.   :8412   Max.   :4388   Max.   :6179  


In [4]:
print(EuStockMarkets[,'DAX']) # 输出所有行，DAX列数据，直接使用列名称访问 

Time Series:
Start = c(1991, 130) 
End = c(1998, 169) 
Frequency = 260 
   [1] 1628.75 1613.63 1606.51 1621.04 1618.16 1610.61 1630.75 1640.17 1635.47
  [10] 1645.89 1647.84 1638.35 1629.93 1621.49 1624.74 1627.63 1631.99 1621.18
  [19] 1613.42 1604.95 1605.75 1616.67 1619.29 1620.49 1619.67 1623.07 1613.98
  [28] 1631.87 1630.37 1633.47 1626.55 1650.43 1650.06 1654.11 1653.60 1501.82
  [37] 1524.28 1603.65 1622.49 1636.68 1652.10 1645.81 1650.36 1651.55 1649.88
  [46] 1653.52 1657.51 1649.55 1649.09 1646.41 1638.65 1625.80 1628.64 1632.22
  [55] 1633.65 1631.17 1635.80 1621.27 1624.70 1616.13 1618.12 1627.80 1625.79
  [64] 1614.80 1612.80 1605.47 1609.32 1607.48 1607.48 1604.89 1589.12 1582.27
  [73] 1567.99 1568.16 1569.71 1571.74 1585.41 1570.01 1561.89 1565.18 1570.34
  [82] 1577.00 1590.29 1572.72 1572.07 1579.19 1588.73 1586.01 1579.77 1572.58
  [91] 1568.09 1578.21 1573.94 1582.06 1610.18 1605.16 1623.84 1615.26 1627.08
 [100] 1626.97 1605.70 1589.70 1589.70 1603.26 1599.75 1590

In [ ]:
print(EuStockMarkets[,1]) # 输出所有行，第一列（德国DAX指数）数据，编写大型程序时显然不够直观
# 与上一行命令等价,注意R语言的索引都是从1开始的

In [6]:
# 查看整个矩阵的数据，坏处是还需要手动关闭打开的页面 
View(EuStockMarkets) 

ERROR: Error in View(EuStockMarkets): 'View()' not yet supported in the Jupyter R kernel


In [10]:
#计算矩阵每一行的和生成一个新向量 
rowTotal <- rowSums(EuStockMarkets) 
# print(rowTotal)

In [12]:
# 以列方式将每一行和向量接在矩阵之后形成有5列的新矩阵 
EuStockMarkets <- cbind(EuStockMarkets,rowTotal) 
# View(EuStockMarkets) 
print(summary(EuStockMarkets))

 EuStockMarkets.EuStockMarkets.DAX EuStockMarkets.EuStockMarkets.SMI
 Min.   :1402                      Min.   :1587                     
 1st Qu.:1744                      1st Qu.:2166                     
 Median :2141                      Median :2796                     
 Mean   :2531                      Mean   :3376                     
 3rd Qu.:2722                      3rd Qu.:3812                     
 Max.   :6186                      Max.   :8412                     
 EuStockMarkets.EuStockMarkets.CAC EuStockMarkets.EuStockMarkets.FTSE
 Min.   :1611                      Min.   :2281                      
 1st Qu.:1875                      1st Qu.:2843                      
 Median :1992                      Median :3247                      
 Mean   :2228                      Mean   :3566                      
 3rd Qu.:2274                      3rd Qu.:3994                      
 Max.   :4388                      Max.   :6179                      
 EuStockMarkets.rowTotal   

In [13]:
# 计算矩阵每一列的和生成一个新向量 
colTotal <- colSums(EuStockMarkets) 
# 以行方式将每一行和向量接在矩阵之后形成一个有新累加和行的矩阵 
EuStockMarkets <- rbind(EuStockMarkets,colTotal) 
print(tail(EuStockMarkets))

         EuStockMarkets.EuStockMarkets.DAX EuStockMarkets.EuStockMarkets.SMI
                                   5460.43                            7721.3
                                   5285.78                            7447.9
                                   5386.94                            7607.5
                                   5355.03                            7552.6
                                   5473.72                            7676.3
colTotal                        4707021.80                         6279776.1
         EuStockMarkets.EuStockMarkets.CAC EuStockMarkets.EuStockMarkets.FTSE
                                    3939.5                             5587.6
                                    3846.0                             5432.8
                                    3945.7                             5462.2
                                    3951.7                             5399.5
                                    3995.0                             

dataframe是矩阵的进阶版,形式和Excel比较相似    
每一列可以看做是一个向量，类型相同(去掉列属性)；不同列数据之间可以有不同类型    
同列表的重要区别是：数据框要求每一列数据长度相同    
dataframe的每一行可以看作是一条记录，每一列看做是记录的某一个属性    
dataframe是金融大数据处理中非常重要的数据结构，用途很广必须深入了解    

In [19]:
my_df <- data.frame(symbols=c('MSFT','KO','CSCO'),price=c(40.40,40.56,23.02),currency=rep('USD',3),country=rep('USA',3),type=rep('STOCK',3)) 
my_df

symbols price currency country type 
1 MSFT    40.40 USD      USA     STOCK
2 KO      40.56 USD      USA     STOCK
3 CSCO    23.02 USD      USA     STOCK

In [20]:
print(class(my_df)) 
cat('df数据框行数为：',nrow(my_df),'\ndf数据框列数为：',ncol(my_df),'\n',sep=' ') 
cat('列数（属性）数量：',length(my_df),'\n',sep=' ') 

[1] "data.frame"
df数据框行数为： 3 
df数据框列数为： 5 
列数（属性）数量： 5 


In [21]:
print(my_df[1,]) # 通过行号访问数据框的一行 

  symbols price currency country  type
1    MSFT  40.4      USD     USA STOCK


In [22]:
print(my_df[,2])  # 通过列号访问数据框的一列 

[1] 40.40 40.56 23.02


In [23]:
print(my_df$price) # 用列名称是更好、更直观的方式 

[1] 40.40 40.56 23.02


如果需要多次访问数据框中的数据列可以将数据框名称加入到搜索路径中 
这样就可以直接使用数据列名称 

In [26]:
attach(my_df) 
print(currency) 
print(type) 

[1] USD USD USD
Levels: USD
[1] STOCK STOCK STOCK
Levels: STOCK


In [27]:
detach(my_df)
print(type) 

ERROR: Error in print(type): 找不到对象'type'


### 列表 
列表使用list()函数来定义，列表中的每个元素可以是单个变量或者是向量，甚至是另一个列表 
列表中每个向量的长度可以不同，这是列表和数据框的重要区别 
R语言中的列表更像是有序的字典.   
数据框是一种形式特殊的列表,python中的pandas的dataframe可通过[{},{},...,{}]转化.

In [28]:
lst <- list(symbols=c('MSFT','KO','CSCO'),price=c(40.40,40.56,23.02),currency='USD',country='USA',type='STOCK') 
lst 
print(length(lst)) # 共5个元素

$symbols
[1] "MSFT" "KO"   "CSCO"

$price
[1] 40.40 40.56 23.02

$currency
[1] "USD"

$country
[1] "USA"

$type
[1] "STOCK"

[1] 5


In [29]:
str(lst) # 更友好的打印

List of 5
 $ symbols : chr [1:3] "MSFT" "KO" "CSCO"
 $ price   : num [1:3] 40.4 40.6 23
 $ currency: chr "USD"
 $ country : chr "USA"
 $ type    : chr "STOCK"


In [18]:
lst <- list(symbols=c('MSFT','KO','CSCO'),price=c(40.40,40.56,23.02),currency='USD',country='USA',type='STOCK') 
print(lst[1])
print(lst$symbols)
print(lst[[1]]) # 该列表的第一个元素是一个向量symbols
print(lst$symbols[1]) # 该列表中symbols向量的第一个元素

$symbols
[1] "MSFT" "KO"   "CSCO"

[1] "MSFT" "KO"   "CSCO"
[1] "MSFT" "KO"   "CSCO"
[1] "MSFT"


个人认为R语言里的list有点像有序字典

In [20]:
# 在列表末尾添加一个新的元素TradeDate
names(lst) 
lst$TradeDate <- as.Date(rep('2014-4-17',3)) 
names(lst)

[1] "symbols"  "price"    "currency" "country"  "type"

[1] "symbols"   "price"     "currency"  "country"   "type"      "TradeDate"

names(lst) 有点像把有序字典的keys取出来

In [22]:
print(lst$TradeDate[1])
print(lst$TradeDate[2])
print(lst$TradeDate[3])

[1] "2014-04-17"
[1] "2014-04-17"
[1] "2014-04-17"


In [24]:
print(lst$TradeDate[0])
print(lst$TradeDate[4])

[1] "Date of length 0"
[1] NA


In [26]:
z <- list(plantform = rep('FXCM',3)) 
lst <- append(lst,z,after=0) # 在list头部加入
names(lst) 
str(lst)

[1] "plantform" "symbols"   "price"     "currency"  "country"   "type"     
[7] "TradeDate"

List of 7
 $ plantform: chr [1:3] "FXCM" "FXCM" "FXCM"
 $ symbols  : chr [1:3] "MSFT" "KO" "CSCO"
 $ price    : num [1:3] 40.4 40.6 23
 $ currency : chr "USD"
 $ country  : chr "USA"
 $ type     : chr "STOCK"
 $ TradeDate: Date[1:3], format: "2014-04-17" "2014-04-17" ...


In [27]:
# 删除列表中的指定项
names(lst) 
lst$price <- NULL 
names(lst)

[1] "plantform" "symbols"   "price"     "currency"  "country"   "type"     
[7] "TradeDate"

[1] "plantform" "symbols"   "currency"  "country"   "type"      "TradeDate"